### ISSUE TITLE
ImportError: cannot import name url_encode

### ISSUE THREAD

**Issue by alex-dorokhov** [yandexmobile/appmetrica-funnels#10]
Hi, I'm trying to run the project using docker-compose.
1. I set TOKEN and API_KEYS in _docker-compose.yaml_
2. I run _docker-compose up_ :

```
> docker-compose up
Creating network "appmetrica-funnels_default" with the default driver
Creating appmetrica-funnels_clickhouse_1 ... done
Creating appmetrica-funnels_web_1        ... done
Attaching to appmetrica-funnels_clickhouse_1, appmetrica-funnels_web_1
clickhouse_1  | Processing configuration file '/etc/clickhouse-server/config.xml'.
clickhouse_1  | Merging configuration file '/etc/clickhouse-server/config.d/docker_related_config.xml'.
clickhouse_1  | Include not found: clickhouse_remote_servers
clickhouse_1  | Include not found: clickhouse_compression
clickhouse_1  | Logging trace to /var/log/clickhouse-server/clickhouse-server.log
clickhouse_1  | Logging errors to /var/log/clickhouse-server/clickhouse-server.err.log
clickhouse_1  | Processing configuration file '/etc/clickhouse-server/users.xml'.
clickhouse_1  | Include not found: networks
clickhouse_1  | Saved preprocessed configuration to '/var/lib/clickhouse//preprocessed_configs/users.xml'.
web_1         | Traceback (most recent call last):
web_1         |   File "./run.py", line 18, in <module>
web_1         |     from app.run import main as app
web_1         |   File "/usr/src/app/run.py", line 17, in <module>
web_1         |     from forms import ParamsForm
web_1         |   File "/usr/src/app/forms.py", line 13, in <module>
web_1         |     from flask_wtf import Form
web_1         |   File "/usr/local/lib/python2.7/site-packages/flask_wtf/__init__.py", line 17, in <module>
web_1         |     from .recaptcha import *
web_1         |   File "/usr/local/lib/python2.7/site-packages/flask_wtf/recaptcha/__init__.py", line 2, in <module>
web_1         |     from .fields import *
web_1         |   File "/usr/local/lib/python2.7/site-packages/flask_wtf/recaptcha/fields.py", line 3, in <module>
web_1         |     from . import widgets
web_1         |   File "/usr/local/lib/python2.7/site-packages/flask_wtf/recaptcha/widgets.py", line 5, in <module>
web_1         |     from werkzeug import url_encode
web_1         | ImportError: cannot import name url_encode
appmetrica-funnels_web_1 exited with code 1
clickhouse_1  | Processing configuration file '/etc/clickhouse-server/config.xml'.
clickhouse_1  | Merging configuration file '/etc/clickhouse-server/config.d/docker_related_config.xml'.
clickhouse_1  | Include not found: clickhouse_remote_servers
clickhouse_1  | Include not found: clickhouse_compression
clickhouse_1  | Saved preprocessed configuration to '/var/lib/clickhouse//preprocessed_configs/config.xml'.
```

3. I open http://localhost:5000 in browser, but the browser can't find anything.

What am I doing wrong?

OS: MacOS
Docker: 19.03.12

**Comment by tna0y** [comment]
Can be hotfixed by adding `Werkzeug==0.16.1` line to `requirements.txt` file

**Comment by ghost** [comment]
We have  recently released funnels in our AppMetrica interface, so you can use them there.
